### ISSUE TITLE
AnnouncerPlus is not registered with the PlaceholderAPI

### ISSUE THREAD

**Issue by AkariDream** [jpenilla/AnnouncerPlus#106]
placeholders do not work correctly
 "/papi list" does not show AnnouncerPlus

**Comment by jpenilla** [comment]
This is correct behavior. AP does not add a placeholder expansion/any placeholders. The PAPI integration is that existing placeholders are able to be used in AP messages.

**Comment by AkariDream** [comment]
when I use placeholders. he will display placeholders directly instead of content. e.g. %player% %essentials_nickname%
and not the player name
