### ISSUE TITLE
[Bug Report] Clickable message is actually not clickable in MOTD

### ISSUE THREAD

**Issue by Akiranya** [jpenilla/AnnouncerPlus#120]
**Describe the bug**
As the title.

**To Reproduce**
1. Write some clickable message following the MiniMessage format in the motd
2. Join the server and click the clickable message
3. The message is actually not clickable

**Expected behavior**
A clickable message in the motd should be actually clickable.

**Screenshots**

**Server Software and Version:**
 - Vendor: git-Purpur-1761 (MC: 1.19.2)
 - Minecraft Version: 1.19.2
 - Output of /version command: Current: git-Purpur-1761 (MC: 1.19.2)*
Previous: git-Purpur-1735 (MC: 1.19)
* You are running the latest version

**Additional context**
The clickable message I set in the motd is:

```
    join-messages=[
        "",
        "<aqua>欢迎来到</aqua> <green><b>生存服</b></green><gray>·</gray><light_purple>第十七周目</light_purple> !",
        "点击下方 [链接] 查看更多信息 !",
        "<hover:show_text:'点击打开服务器 Wiki'><click:open_url:'https://wiki.mewcraft.cc'>[<color:#55ff99>Wiki</color>]</click></hover> <hover:show_text:'点击打开上古茶馆'><click:open_url:'https://bbs.mewcraft.cc'>[<color:#ffff99>茶馆</color>]</click></hover> <hover:show_text:'点击加入玩家交流群'><click:open_url:'https://qm.qq.com/cgi-bin/qm/qr?k=hXMrpi7526OY0Q0SDZemVw1VJEB58Cyh&authKey=Mp6lZ5bZ1l58nDf99s7z0NudcugDWbNx3wVSeKFSSyiBSL7VupJuQZoPmnBWm9gd&noverify=0'>[<color:#ff88ff>QQ群</color>]</click></hover> <hover:show_text:'点击查看服务器最近改动'><click:open_url:'https://bbs.mewcraft.cc/d/667-mc119'>[<color:#ffaa99>近期更新</color>]</click></hover>",
        "",
        "<aqua>当前内部版本</aqua>: <b><gold>Beta 0.1.15</gold></b>",
        ""
    ]
```

See [here](https://webui.adventure.kyori.net/?x=JjZm1K3NmW) for MiniMessage preview.

**Comment by Akiranya** [comment]
I also tried `/ap send ` to send clickable message to players. It seems it's also not clickable.

Is this feature intended ? ;w;

**Comment by jpenilla** [comment]
You need the dev build for 1.19.1/2.

**Comment by Akiranya** [comment]
Didn't know there are dev builds. Problem solved! Thank you for the information
