### ISSUE TITLE
[Bug Report] Color codes do not work in Minecraft 1.12.2

### ISSUE THREAD

**Issue by TeQTabanca** [jpenilla/AnnouncerPlus#128]
**Describe the bug**
I tried all the message commands, I also tried on the test server, but when I type the color codes, the color code I wrote does not appear.

**To Reproduce**
1. /ap <all_message_commands> &b&lTest &e&lMessage
2. Color code will not appear.

**Expected behavior**
I want color codes like &a, &e&l, &f&o, &b&k, &7&m, &5&n, &r to work.

**Screenshots**

![announcerplus color codes issue](https://user-images.githubusercontent.com/89253304/196908925-215acb99-adad-4634-a354-e49365736291.png)

**Server Software and Version:**
 - Vendor: Spigot
 - Minecraft Version: 1.12.2
 - Output of /version command: This server is running CraftBukkit version git-Spigot-79a30d7-f4830a1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.

**Comment by jpenilla** [comment]
AP does not support legacy formatting, only [MiniMessage](https://docs.adventure.kyori.net/minimessage.html#format)
