### ISSUE TITLE
[Bug Report] join-sounds section

### ISSUE THREAD

**Issue by YKDZ** [jpenilla/AnnouncerPlus#164]
**Describe the bug**
https://mcpaste.com/a8a77a2eb78dace79b13a7569aeb4641
https://mcpaste.com/cd48438fe23c9dd44e54af1a23a92b77
If the comments in the join-sounds configuration are removed, an error will occur and the server will not be able to start.

**To Reproduce**
1. Copy the file
2. Start the server

**Server Software and Version:**
 - Vendor: Purpur
 - Minecraft Version: 1.19.3
 - Output of /version command: Current: git-Purpur-1933 (MC: 1.19.3)*

**Comment by jpenilla** [comment]
If you don't want join sounds, set it to an empty array `[]`.
