### ISSUE TITLE
[Bug Report] Boss bar /actionbar/toast/title/sound does not work on folia

### ISSUE THREAD

**Issue by cgw2023** [jpenilla/AnnouncerPlus#165]
**Describe the bug**
Boss bar, action bar, toast, title  and sound function does not work in folia 1.20.1
I understand that folia disabled Bossbar command, if that cause boss bar not working, thats ok. But I don't know why action bar, toast, title and sound function is not functioning, folia FAQ didn't mention that these are disabled:
![image](https://github.com/jpenilla/AnnouncerPlus/assets/136877036/4b21dec6-efc4-43c7-84e1-cc1bb77f7307)

**To Reproduce**
1. Put plugin into plugins folder and run with default config
2. (optional, adjust the time interval to 1 Second)

**Expected behavior**
Default demo.conf will show some random action bar, title, toast sound, bossbar and more

**Screenshots**
Only the commands working
![image](https://github.com/jpenilla/AnnouncerPlus/assets/136877036/2ea7fa5e-04bd-4364-a69a-e49294eb4767)

**Server Software and Version:**
 - Vendor: folia
 - Minecraft Version:  1.20.1
This server is running Folia version git-Folia-18 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 7c6e251 on HEAD)
You are -17 version(s) behind

**Additional context**
AnnouncerPlus-1.3.5.jar

**Comment by jpenilla** [comment]
Cannot reproduce, APs boss bars, toasts, action bars, titles, and sounds all work fine for me on latest Folia.
