### ISSUE TITLE
[Bug Report] When i want send toast message with Fire icon, i receive this error

### ISSUE THREAD

**Issue by pjindras** [jpenilla/AnnouncerPlus#177]
When i want send toast message with Fire icon, i receive this error

18:22:45[WARN] Exception in thread "pool-48-thread-5" java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null
18:22:45[WARN] at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapIterator.nextEntry(Object2ObjectOpenHashMap.java:631)
18:22:45[WARN] at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$KeyIterator.next(Object2ObjectOpenHashMap.java:1034)
18:22:45[WARN] at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftMetaItem.<init>(CraftMetaItem.java:439)
18:22:45[WARN] at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:615)
18:22:45[WARN] at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:309)
18:22:45[WARN] at org.bukkit.craftbukkit.v1_20_R1.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:301)
18:22:45[WARN] at Vulcan-2.7.5.jar//me.frep.vulcan.spigot.Vulcan_LG.Vulcan_o(Vulcan_LG.java:781)
18:22:45[WARN] at Vulcan-2.7.5.jar//me.frep.vulcan.spigot.Vulcan_GK.Vulcan_M(Vulcan_GK.java:43)
18:22:45[WARN] at Vulcan-2.7.5.jar//me.frep.vulcan.spigot.Vulcan_t_.lambda$onPacketPlayReceive$0(Vulcan_t_.java:64)
18:22:45[WARN] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
18:22:45[WARN] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
18:22:45[WARN] at java.base/java.lang.Thread.run(Unknown Source)

**Comment by jpenilla** [comment]
Please open a new issue if this occurs without Vulcan-2.7.5.jar
