### ISSUE TITLE
[Bug Report] Incredible lag when announcement is sent

### ISSUE THREAD

**Issue by Yertled** [jpenilla/AnnouncerPlus#198]
**Describe the bug**
When an announcement is being sent in-game, the server totally freezes for a few seconds, even with low player count. (20)

**To Reproduce**
Send an announcement.

**Screenshots**
(https://clipchamp.com/watch/wfjwpSFK7M3)

**Server Software and Version:**
 - Vendor: Pufferfish+ version git-PufferfishPlus-33
 - Minecraft Version: 1.20.4
 - This server is running Pufferfish+ version git-PufferfishPlus-33 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 94fa469 on HEAD)
 
**Additional context**
This only started happening recently. Think it was after 1.20.4 update.

**Comment by jpenilla** [comment]
Advancement displays weren't working on 1.20.4 until https://github.com/jpenilla/AnnouncerPlus/commit/53735e37583a9830059e848c8ca88f9cd0789b96, so I'm not sure how this would happen without something like ViaVersion being involved.
