### ISSUE TITLE
[Bug Report] Recursive scheduling of asynchronous tasks in case of missing messages; 

### ISSUE THREAD

**Issue by HarvelsX** [jpenilla/AnnouncerPlus#224]
**Describe the bug**
If no messages are available on the broadcast, the plugin cyclically schedules to process a message queue with no messages in it, which causes constant scheduling.

**To Reproduce**
1. Set -Xms=-Xmx=1G
2. Remove all messages from demo.conf (`messages=[]`)
3. Wait a while (1 day?)
4. See the memory leak

**Expected behavior**
Ignoring scheduling of tasks without messages, or optimizing scheduling

**Screenshots**
![image](https://github.com/jpenilla/AnnouncerPlus/assets/90945793/3e40f117-c74d-451a-a441-640cb260e3bb)
![image](https://github.com/jpenilla/AnnouncerPlus/assets/90945793/9edce017-fe19-44bb-9340-9f816471a878)

**Server Software and Version:**
 - Vendor: Any
 - Minecraft Version: 1.20.4
 - Output of /version command: git-Purpur-2176 (MC: 1.20.4)*

**Suggestions for solutions**
Remove recursive scheduling
```patch
diff --git a/src/main/kotlin/xyz/jpenilla/announcerplus/config/message/MessageConfig.kt b/src/main/kotlin/xyz/jpenilla/announcerplus/config/message/MessageConfig.kt
index 699be5b..d4a8fe9 100644
--- a/src/main/kotlin/xyz/jpenilla/announcerplus/config/message/MessageConfig.kt
+++ b/src/main/kotlin/xyz/jpenilla/announcerplus/config/message/MessageConfig.kt
@@ -204,15 +204,13 @@ class MessageConfig : SelfSavable<CommentedConfigurationNode>, KoinComponent {
   @Transient
   private val broadcastQueue = ArrayDeque<Message>()
 
-  fun broadcast(skipInitialDelay: Boolean = false) {
-    stop()
-    broadcastQueue.clear()
-    broadcastQueue.addAll(shuffledMessages())
-    broadcastTask = announcerPlus.asyncTimer(if (skipInitialDelay) 0L else initialDelay.ticks, interval.ticks) {
+  fun broadcast() {
+    broadcastTask = announcerPlus.asyncTimer(initialDelay.ticks, interval.ticks) {
       if (broadcastQueue.isNotEmpty()) {
         broadcast(broadcastQueue.removeFirst())
       } else {
-        broadcast(true)
+        // Removed recursion to prevent out of memory errors with empty messages
+        broadcastQueue.addAll(shuffledMessages())
       }
     }
   }
```

**Comment by jpenilla** [comment]
Old tasks were already being cancelled, I've removed the redundant scheduling when there is no messages however the real impact is probably next to zero.

**Comment by jpenilla** [comment]
If the file is not too large I guess I can take a look, but I do not see any way for a meaningful memory leak (or any memory leak at all) to happen here, the tasks are not capturing the previous task or anything like that.

**Comment by HarvelsX** [comment]
@jpenilla, here are some screenshots from Eclipse MAT and the dump itself
![image](https://github.com/jpenilla/AnnouncerPlus/assets/90945793/ddb4f16f-f7e5-4d43-b615-dab18800553d)
![image](https://github.com/jpenilla/AnnouncerPlus/assets/90945793/8fa880a4-d302-4dc8-99dd-ea1051ed0039)

hprof: https://drive.google.com/file/d/1RMt15DhFI2G-1e9aZ5QXhq1kCJlNHQT8/view

**Comment by jpenilla** [comment]
Looks like some sort of bug with the async scheduler or another plugin

f201bb1ef190f0c61385dcaca560f4aa71bb53a1 this will avoid the issue

**Comment by HarvelsX** [comment]
> another plugin
It's also a possibility, I'll continue to look into issue when similar problems arise.

Thanks a lot for the very fast support, you are the best!
