### ISSUE TITLE
[Bug Report] Plugin won't run on 1.12.2 (AnnouncerPlus version 1.3.8)

### ISSUE THREAD

**Issue by TheJoshue** [jpenilla/AnnouncerPlus#234]
**Describe the bug**
This happens on server load, this is the logs
https://mclo.gs/vkNjIcN

**To Reproduce**
1. Make sure you have AnnouncerPlus plugin in `plugins` folder
2. Run the server
3. See error

**Expected behavior**
It should load

**Screenshots**
/

**Server Software and Version:**
 - Vendor: `Paper`
 - Minecraft Version: `1.12.2`
 - Output of /version command: `This server is running Paper version git-Paper-1620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)] 

**Additional context**
/

**Comment by TheJoshue** [comment]
I just want to confirm that i have just now tested previous release of AnnouncerPlus plugin - version `1.3.7` - it does not have this error, it works fine
The version that does not work and which i have reported here is latest one (`1.3.8`)

**Comment by jpenilla** [comment]
Please try with the 1.4 snapshots from jenkins https://jenkins.jpenilla.xyz/job/AnnouncerPlus/

**Comment by TheJoshue** [comment]
> Please try with the 1.4 snapshots from jenkins https://jenkins.jpenilla.xyz/job/AnnouncerPlus/

Sorry, regular or `not-shadowed` jar file?

**Comment by jpenilla** [comment]
The regular jar, not-shadowed won't run (at some point I should adjust jenkins to not store that one)

**Comment by TheJoshue** [comment]
> The regular jar, not-shadowed won't run (at some point I should adjust jenkins to not store that one)

Works perfectly, thanks a lot!
